### ISSUE TITLE
Install downloaded "APKS" file?

### ISSUE THREAD

**Issue by Ethan-VisualVocal** [nkalra0123/splitapkinstall#1]
Does this allow installing downloaded APKS files? If so, how do I get that to work -- I can't seem to figure it out.

(I do understand that it allows sharing of already installed apps that are generated from AAB files.)

**Comment by nkalra0123** [comment]
Yes, 
If you have an apk which you have downloaded, or you have splits that someone has shared with you, You can install them.

Open the app, click on the floating icon (download icon), it will open a file manager ui,
Select the apk, or multiple apks (in case of split apps)
give install permission
Apk will be installed.

**Comment by nkalra0123** [comment]
Explained, If still unable to understand, please reopen
